wandb_version: 1

activation:
  value: relu
batchSize:
  value: 32
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 10
n:
  value: 0.01
no_of_hidden_layers:
  value: 5
no_of_neuron:
  value: 128
optimizer:
  value: batch
