wandb_version: 1

activation:
  value: tanh
batchSize:
  value: 32
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 5
n:
  value: 0.001
no_of_hidden_layers:
  value: 3
no_of_neuron:
  value: 128
optimizer:
  value: Nadam
