wandb_version: 1

activation:
  value: relu
batchSize:
  value: 64
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 5
n:
  value: 0.01
no_of_hidden_layers:
  value: 4
no_of_neuron:
  value: 128
optimizer:
  value: momentum
