wandb_version: 1

activation:
  value: relu
alpha:
  value: 0.001
batchSize:
  value: 32
initialization:
  value: random
input_neuron:
  value: 784
iter:
  value: 8
loss_fn:
  value: mean_square
n:
  value: 0.001
no_of_hidden_layers:
  value: 4
no_of_neuron:
  value: 32
optimizer:
  value: nestrov
