wandb_version: 1

activation:
  value: relu
alpha:
  value: 0
batchSize:
  value: 16
initialization:
  value: random
input_neuron:
  value: 784
iter:
  value: 10
loss_fn:
  value: mean_square
n:
  value: 0.01
no_of_hidden_layers:
  value: 4
no_of_neuron:
  value: 64
optimizer:
  value: rmsProp
