wandb_version: 1

activation:
  value: sigmoid
batchSize:
  value: 16
initialization:
  value: relu
input_neuron:
  value: 784
iter:
  value: 10
n:
  value: 0.001
no_of_hidden_layers:
  value: 3
no_of_neuron:
  value: 128
optimizer:
  value: adam
