wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.2
    start_time: 1679075071.081663
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.11.2
      5: 0.13.10
      8:
      - 3
      - 5
activation:
  desc: null
  value: tanh
alpha:
  desc: null
  value: 0.0001
batchSize:
  desc: null
  value: 32
initialization:
  desc: null
  value: xavier
input_neuron:
  desc: null
  value: 784
iter:
  desc: null
  value: 5
loss_fn:
  desc: null
  value: mean_square
n:
  desc: null
  value: 0.01
no_of_hidden_layers:
  desc: null
  value: 3
no_of_neuron:
  desc: null
  value: 128
optimizer:
  desc: null
  value: Nadam
