wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.0001
batchSize:
  value: 16
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 5
loss_fn:
  value: cross_entropy
n:
  value: 0.005
no_of_hidden_layers:
  value: 2
no_of_neuron:
  value: 64
optimizer:
  value: rmsProp
