wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.0001
batchSize:
  value: 32
initialization:
  value: random
input_neuron:
  value: 784
iter:
  value: 8
loss_fn:
  value: cross_entropy
n:
  value: 0.001
no_of_hidden_layers:
  value: 2
no_of_neuron:
  value: 64
optimizer:
  value: Nadam
