wandb_version: 1

activation:
  value: relu
alpha:
  value: 0.0001
batchSize:
  value: 64
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 8
loss_fn:
  value: cross_entropy
n:
  value: 0.01
no_of_hidden_layers:
  value: 2
no_of_neuron:
  value: 128
optimizer:
  value: adam
