wandb_version: 1

activation:
  value: tanh
batchSize:
  value: 32
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 10
n:
  value: 0.01
no_of_hidden_layers:
  value: 4
no_of_neuron:
  value: 64
optimizer:
  value: Nadam
