wandb_version: 1

activation:
  value: sigmoid
batchSize:
  value: 64
initialization:
  value: random
input_neuron:
  value: 784
iter:
  value: 10
n:
  value: 0.01
no_of_hidden_layers:
  value: 5
no_of_neuron:
  value: 64
optimizer:
  value: Nadam
