wandb_version: 1

activation:
  value: tanh
batchSize:
  value: 16
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 10
n:
  value: 0.001
no_of_hidden_layers:
  value: 5
no_of_neuron:
  value: 32
optimizer:
  value: rmsProp
