wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0
batchSize:
  value: 32
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 5
loss_fn:
  value: mean_square
n:
  value: 0.001
no_of_hidden_layers:
  value: 4
no_of_neuron:
  value: 128
optimizer:
  value: adam
