wandb_version: 1

activation:
  value: sigmoid
alpha:
  value: 0
batchSize:
  value: 64
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 8
loss_fn:
  value: mean_square
n:
  value: 0.005
no_of_hidden_layers:
  value: 3
no_of_neuron:
  value: 32
optimizer:
  value: rmsProp
