wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0
batchSize:
  value: 64
initialization:
  value: random
input_neuron:
  value: 784
iter:
  value: 8
loss_fn:
  value: mean_square
n:
  value: 0.005
no_of_hidden_layers:
  value: 2
no_of_neuron:
  value: 64
optimizer:
  value: Nadam
