wandb_version: 1

activation:
  value: sigmoid
alpha:
  value: 0.0001
batchSize:
  value: 64
initialization:
  value: xavier
input_neuron:
  value: 784
iter:
  value: 10
loss_fn:
  value: mean_square
n:
  value: 0.001
no_of_hidden_layers:
  value: 2
no_of_neuron:
  value: 128
optimizer:
  value: momentum
