wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.2
    start_time: 1679213246.935122
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.11.2
      5: 0.13.10
      8:
      - 3
      - 5
    visualize:
      my_conf_mat_id:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: my_conf_mat_id_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
activation:
  desc: null
  value: sigmoid
alpha:
  desc: null
  value: 0.001
batchSize:
  desc: null
  value: 16
initialization:
  desc: null
  value: xavier
input_neuron:
  desc: null
  value: 784
iter:
  desc: null
  value: 5
loss_fn:
  desc: null
  value: cross_entropy
n:
  desc: null
  value: 0.01
no_of_hidden_layers:
  desc: null
  value: 3
no_of_neuron:
  desc: null
  value: 64
optimizer:
  desc: null
  value: batch
