wandb_version: 1

activation:
  value: relu
alpha:
  value: 0
batchSize:
  value: 32
initialization:
  value: random
input_neuron:
  value: 784
iter:
  value: 10
loss_fn:
  value: cross_entropy
n:
  value: 0.001
no_of_hidden_layers:
  value: 4
no_of_neuron:
  value: 32
optimizer:
  value: adam
